# Generated by Django 2.1.7 on 2019-04-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealcalendar', '0002_auto_20190421_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
