# Generated by Django 2.1.7 on 2019-04-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20190325_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='c_goal',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='f_goal',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='p_goal',
        ),
        migrations.AddField(
            model_name='profile',
            name='carb_goal',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fat_goal',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='protein_goal',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
