# Generated by Django 2.1.7 on 2019-04-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20190421_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='height',
            new_name='height_ft',
        ),
        migrations.AddField(
            model_name='profile',
            name='height_in',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
