# Generated by Django 2.1.7 on 2019-04-29 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20190429_0458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='height_ft',
            new_name='height',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='height_in',
        ),
    ]
