# Generated by Django 2.1.7 on 2019-04-08 19:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0024_auto_20190408_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 8, 19, 34, 40, 734603, tzinfo=utc)),
        ),
    ]
