# Generated by Django 2.1.7 on 2019-04-14 18:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0024_auto_20190414_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='fiber',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 14, 18, 24, 26, 266797, tzinfo=utc)),
        ),
    ]
