# Generated by Django 2.1.7 on 2019-04-14 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0025_auto_20190414_1824'),
        ('mealbuilder', '0025_auto_20190408_1934'),
    ]

    operations = [
    ]
