# Generated by Django 2.1.7 on 2019-04-15 00:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0027_auto_20190414_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cholesterol',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='food',
            name='magnesium',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='food',
            name='potassium',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='food',
            name='sat_fat',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='food',
            name='sodium',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='food',
            name='sugars',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='food',
            name='total_fat',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='food',
            name='trans_fat',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='meal',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 0, 21, 50, 868281, tzinfo=utc)),
        ),
    ]
