# Generated by Django 2.1.7 on 2019-04-15 00:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0028_auto_20190415_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 0, 40, 21, 267627, tzinfo=utc)),
        ),
    ]
