# Generated by Django 2.1.7 on 2019-04-15 00:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0029_auto_20190415_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='db_num',
        ),
        migrations.AlterField(
            model_name='meal',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 0, 43, 52, 769435, tzinfo=utc)),
        ),
    ]
