# Generated by Django 2.1.7 on 2019-04-15 01:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0030_auto_20190415_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 1, 0, 51, 739066, tzinfo=utc)),
        ),
    ]
