# Generated by Django 2.1.7 on 2019-04-15 01:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0031_auto_20190415_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='db_num',
            field=models.CharField(default=-1, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 1, 23, 39, 136436, tzinfo=utc)),
        ),
    ]
