# Generated by Django 2.1.7 on 2019-04-15 02:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0033_auto_20190415_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 2, 55, 5, 915677, tzinfo=utc)),
        ),
    ]
