# Generated by Django 2.1.7 on 2019-04-19 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0034_auto_20190415_0255'),
        ('mealbuilder', '0027_auto_20190415_0332'),
    ]

    operations = [
    ]
