# Generated by Django 2.1.7 on 2019-04-19 19:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0035_merge_20190419_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 19, 19, 19, 46, 352126, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealbuilder.Meal'),
        ),
    ]
