# Generated by Django 2.1.7 on 2019-04-22 02:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0039_auto_20190421_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 2, 38, 45, 890552, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='savedmeal',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 2, 38, 45, 890552, tzinfo=utc)),
        ),
    ]
