# Generated by Django 2.1.7 on 2019-04-22 02:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0041_auto_20190421_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 2, 45, 54, 241906, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='savedmeal',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 2, 45, 54, 244905, tzinfo=utc)),
        ),
    ]
