# Generated by Django 2.1.7 on 2019-04-22 22:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0042_auto_20190421_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 22, 31, 13, 237450, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='carb_actual',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='fat_actual',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Profile'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='protein_actual',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='savedmeal',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 22, 31, 13, 237450, tzinfo=utc)),
        ),
    ]
