# Generated by Django 2.1.7 on 2019-04-23 00:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0043_auto_20190422_1531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.RemoveField(
            model_name='savedmeal',
            name='food',
        ),
        migrations.RemoveField(
            model_name='savedmeal',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='savedplan',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='savedplan',
            name='profile',
        ),
        migrations.AlterField(
            model_name='meal',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 23, 0, 56, 56, 45869, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='SavedMeal',
        ),
        migrations.DeleteModel(
            name='SavedPlan',
        ),
    ]
