# Generated by Django 2.1.7 on 2019-04-23 01:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0044_auto_20190422_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 23, 1, 1, 41, 758746, tzinfo=utc)),
        ),
    ]
