# Generated by Django 2.1.7 on 2019-04-25 01:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0045_auto_20190422_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['create_date']},
        ),
        migrations.RemoveField(
            model_name='meal',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='meal',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 25, 1, 42, 36, 761978, tzinfo=utc)),
        ),
    ]
