# Generated by Django 2.1.7 on 2019-04-29 19:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0046_auto_20190424_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 29, 19, 6, 5, 90222, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='meal',
            field=models.ManyToManyField(null=True, related_name='plans', to='mealbuilder.Meal'),
        ),
    ]
