# Generated by Django 2.1.7 on 2019-05-04 04:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0048_auto_20190501_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='carb_actual',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='fat_actual',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='protein_actual',
        ),
        migrations.AddField(
            model_name='plan',
            name='calories',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='cholesterol',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='fiber',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='magnesium',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='potassium',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='sat_fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='sodium',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='sugars',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='total_fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='trans_fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='cholesterol',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 4, 48, 7, 147722, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fiber',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='magnesium',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='potassium',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='sat_fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='sodium',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='sugars',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='total_fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='trans_fat',
            field=models.FloatField(default=0),
        ),
    ]
