# Generated by Django 2.1.7 on 2019-05-02 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0048_auto_20190501_0944'),
        ('mealbuilder', '0047_auto_20190429_1639'),
    ]

    operations = [
    ]
