# Generated by Django 2.1.7 on 2019-05-05 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0049_auto_20190503_2148'),
        ('mealbuilder', '0049_merge_20190502_1319'),
    ]

    operations = [
    ]
