# Generated by Django 2.1.7 on 2019-05-04 23:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mealbuilder', '0051_auto_20190504_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 23, 30, 41, 526798, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mealfood',
            name='carbs',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mealfood',
            name='fat',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mealfood',
            name='protein',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mealfood',
            name='quantity',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
